//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.Simulation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.Simulation.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem during runtime: {0} ähnelt.
        /// </summary>
        internal static string SimulationPluginExcetionIntro {
            get {
                return ResourceManager.GetString("SimulationPluginExcetionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} from {3} ähnelt.
        /// </summary>
        internal static string SimulationPluginKicklistEntry {
            get {
                return ResourceManager.GetString("SimulationPluginKicklistEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following colonies are not valid anymore:  ähnelt.
        /// </summary>
        internal static string SimulationPluginKicklistHead {
            get {
                return ResourceManager.GetString("SimulationPluginKicklistHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AntMe! - Simulation ähnelt.
        /// </summary>
        internal static string SimulationPluginMessageBoxTitle {
            get {
                return ResourceManager.GetString("SimulationPluginMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Following rights are not granted in the settings: ähnelt.
        /// </summary>
        internal static string SimulationPluginRightsLocked {
            get {
                return ResourceManager.GetString("SimulationPluginRightsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This colony creates a ruleViolation with current settings: {0} ähnelt.
        /// </summary>
        internal static string SimulationPluginRuleViolation {
            get {
                return ResourceManager.GetString("SimulationPluginRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesAuthorFormat {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesAuthorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access to a database ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesDbAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesDbAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access to the file system ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesIoAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesIoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access to the network ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesNetAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesNetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full access limitation ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesNoAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No further information available. ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesNoAdditionalInfos {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesNoAdditionalInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ant references external assembly or assemblies. ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesRefAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesRefAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties of {0} ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesTitle {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access to the user interface ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesUiAccess {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesUiAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string SimulatorPluginAntPropertiesUnknown {
            get {
                return ResourceManager.GetString("SimulatorPluginAntPropertiesUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ant simulation ähnelt.
        /// </summary>
        internal static string SimulatorPluginDescription {
            get {
                return ResourceManager.GetString("SimulatorPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulation v1.6 ähnelt.
        /// </summary>
        internal static string SimulatorPluginName {
            get {
                return ResourceManager.GetString("SimulatorPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulation has not been started. ähnelt.
        /// </summary>
        internal static string SimulatorPluginNotStarted {
            get {
                return ResourceManager.GetString("SimulatorPluginNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} coun&apos;t be loaded. The detailed errormessage is &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string SimulatorPluginTeamSetupFileloadException {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupFileloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In the file {0} was no AI found. ähnelt.
        /// </summary>
        internal static string SimulatorPluginTeamSetupNoFolksFound {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupNoFolksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} contains AI, but they are already contained in the list. ähnelt.
        /// </summary>
        internal static string SimulatorPluginTeamSetupStillLoaded {
            get {
                return ResourceManager.GetString("SimulatorPluginTeamSetupStillLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shows simulation statistics. ähnelt.
        /// </summary>
        internal static string StatisticPluginDescription {
            get {
                return ResourceManager.GetString("StatisticPluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics 1.6 ähnelt.
        /// </summary>
        internal static string StatisticPluginName {
            get {
                return ResourceManager.GetString("StatisticPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yes ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
