//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Plugin.Mdx {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Plugin.Mdx.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anthill ähnelt.
        /// </summary>
        internal static string HovertextAnthillLine1 {
            get {
                return ResourceManager.GetString("HovertextAnthillLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colony: {0} ähnelt.
        /// </summary>
        internal static string HovertextAnthillLine2 {
            get {
                return ResourceManager.GetString("HovertextAnthillLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ({1}) ähnelt.
        /// </summary>
        internal static string HovertextAntLine1 {
            get {
                return ResourceManager.GetString("HovertextAntLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energy: {0} ähnelt.
        /// </summary>
        internal static string HovertextAntLine2 {
            get {
                return ResourceManager.GetString("HovertextAntLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bug ähnelt.
        /// </summary>
        internal static string HovertextBugLine1 {
            get {
                return ResourceManager.GetString("HovertextBugLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energy: {0} ähnelt.
        /// </summary>
        internal static string HovertextBugLine2 {
            get {
                return ResourceManager.GetString("HovertextBugLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apple ähnelt.
        /// </summary>
        internal static string HovertextFruitLine1 {
            get {
                return ResourceManager.GetString("HovertextFruitLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Food: {0} ähnelt.
        /// </summary>
        internal static string HovertextFruitLine2 {
            get {
                return ResourceManager.GetString("HovertextFruitLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sugar ähnelt.
        /// </summary>
        internal static string HovertextSugarLine1 {
            get {
                return ResourceManager.GetString("HovertextSugarLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Food: {0} ähnelt.
        /// </summary>
        internal static string HovertextSugarLine2 {
            get {
                return ResourceManager.GetString("HovertextSugarLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die beaten ähnelt.
        /// </summary>
        internal static string InfoboxColumnBeatenAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnBeatenAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ants ähnelt.
        /// </summary>
        internal static string InfoboxColumnBeatenAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnBeatenAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collected ähnelt.
        /// </summary>
        internal static string InfoboxColumnCollectedFood1 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFood1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Food ähnelt.
        /// </summary>
        internal static string InfoboxColumnCollectedFood2 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFood2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collected ähnelt.
        /// </summary>
        internal static string InfoboxColumnCollectedFruits1 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFruits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fruit ähnelt.
        /// </summary>
        internal static string InfoboxColumnCollectedFruits2 {
            get {
                return ResourceManager.GetString("InfoboxColumnCollectedFruits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoboxColumnColony1 {
            get {
                return ResourceManager.GetString("InfoboxColumnColony1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colony name ähnelt.
        /// </summary>
        internal static string InfoboxColumnColony2 {
            get {
                return ResourceManager.GetString("InfoboxColumnColony2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eaten ähnelt.
        /// </summary>
        internal static string InfoboxColumnEatenAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnEatenAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ants ähnelt.
        /// </summary>
        internal static string InfoboxColumnEatenAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnEatenAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die killed ähnelt.
        /// </summary>
        internal static string InfoboxColumnKilledAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ants ähnelt.
        /// </summary>
        internal static string InfoboxColumnKilledAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die killed ähnelt.
        /// </summary>
        internal static string InfoboxColumnKilledBugs1 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledBugs1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bugs ähnelt.
        /// </summary>
        internal static string InfoboxColumnKilledBugs2 {
            get {
                return ResourceManager.GetString("InfoboxColumnKilledBugs2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string InfoboxColumnPoints1 {
            get {
                return ResourceManager.GetString("InfoboxColumnPoints1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points ähnelt.
        /// </summary>
        internal static string InfoboxColumnPoints2 {
            get {
                return ResourceManager.GetString("InfoboxColumnPoints2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die starved ähnelt.
        /// </summary>
        internal static string InfoboxColumnStarvedAnts1 {
            get {
                return ResourceManager.GetString("InfoboxColumnStarvedAnts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ants ähnelt.
        /// </summary>
        internal static string InfoboxColumnStarvedAnts2 {
            get {
                return ResourceManager.GetString("InfoboxColumnStarvedAnts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display the simulation in 3D ähnelt.
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3D-Visualization ähnelt.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
    }
}
