//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Gui {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Gui.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.antspiel.de ähnelt.
        /// </summary>
        internal static string MainAntspielLink {
            get {
                return ResourceManager.GetString("MainAntspielLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .\\english\\Classes.chm ähnelt.
        /// </summary>
        internal static string MainClassDescriptionPath {
            get {
                return ResourceManager.GetString("MainClassDescriptionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://go.microsoft.com/?linkid=6159907 ähnelt.
        /// </summary>
        internal static string MainForumLink {
            get {
                return ResourceManager.GetString("MainForumLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} fps ähnelt.
        /// </summary>
        internal static string MainFramesPerSecond {
            get {
                return ResourceManager.GetString("MainFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Class-Description available. ähnelt.
        /// </summary>
        internal static string MainMessageBoxNoClassdescriptionMessage {
            get {
                return ResourceManager.GetString("MainMessageBoxNoClassdescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class description ähnelt.
        /// </summary>
        internal static string MainMessageBoxNoClassdescriptionTitle {
            get {
                return ResourceManager.GetString("MainMessageBoxNoClassdescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No help available. ähnelt.
        /// </summary>
        internal static string MainMessageBoxNoTutorialMessage {
            get {
                return ResourceManager.GetString("MainMessageBoxNoTutorialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tutorials ähnelt.
        /// </summary>
        internal static string MainMessageBoxNoTutorialTitle {
            get {
                return ResourceManager.GetString("MainMessageBoxNoTutorialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum ähnelt.
        /// </summary>
        internal static string MainSpeedMaximal {
            get {
                return ResourceManager.GetString("MainSpeedMaximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0.0 fps ähnelt.
        /// </summary>
        internal static string MainStateFramesPerSecond {
            get {
                return ResourceManager.GetString("MainStateFramesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not ready ähnelt.
        /// </summary>
        internal static string MainStateNotReady {
            get {
                return ResourceManager.GetString("MainStateNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paused ähnelt.
        /// </summary>
        internal static string MainStatePaused {
            get {
                return ResourceManager.GetString("MainStatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready ähnelt.
        /// </summary>
        internal static string MainStateReady {
            get {
                return ResourceManager.GetString("MainStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} ähnelt.
        /// </summary>
        internal static string MainStateRoundIndicator {
            get {
                return ResourceManager.GetString("MainStateRoundIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simulating ähnelt.
        /// </summary>
        internal static string MainStateRunning {
            get {
                return ResourceManager.GetString("MainStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .\\english\\Tutorials.chm ähnelt.
        /// </summary>
        internal static string MainTutorialPath {
            get {
                return ResourceManager.GetString("MainTutorialPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A newer version of AntMe! is available on server. You currently use Version {0}, available to download is Version {1}. ähnelt.
        /// </summary>
        internal static string MainUpdateMessage {
            get {
                return ResourceManager.GetString("MainUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AntMe! Update ähnelt.
        /// </summary>
        internal static string MainUpdateTitle {
            get {
                return ResourceManager.GetString("MainUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://www.antme.net ähnelt.
        /// </summary>
        internal static string MainWebsiteLink {
            get {
                return ResourceManager.GetString("MainWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /english/Welcome.htm ähnelt.
        /// </summary>
        internal static string MainWelcomePagePath {
            get {
                return ResourceManager.GetString("MainWelcomePagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name of the plugin is empty. ähnelt.
        /// </summary>
        internal static string PluginItemConstructorPluginHasNoName {
            get {
                return ResourceManager.GetString("PluginItemConstructorPluginHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No plugin was passed to the contructor. ähnelt.
        /// </summary>
        internal static string PluginItemConstructorPluginIsNull {
            get {
                return ResourceManager.GetString("PluginItemConstructorPluginIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin is not in the list of loaded plugins. ähnelt.
        /// </summary>
        internal static string PluginManagerActivateConsumerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerActivateConsumerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin is not in the list of loaded plugins. ähnelt.
        /// </summary>
        internal static string PluginManagerActivateProducerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerActivateProducerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There were problems loading plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerPluginCommonProblems {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginCommonProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two different versions are available for plugin {0} ({1}). The one with the higher version number will be loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerPluginNewerVersion {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A higher version of plugin {0} ({1}) is already loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerPluginNewerVersionLoaded {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginNewerVersionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings for plugin {0} ({1}) could not be loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerPluginSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem when saving settings of plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerPluginSettingsSaveFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerPluginSettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A problem occured in Plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerConsumerVisibilitySetFailed {
            get {
                return ResourceManager.GetString("PluginManagerConsumerVisibilitySetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin is not in the list of currently loaded plugins. ähnelt.
        /// </summary>
        internal static string PluginManagerDeactivateConsumerNotInList {
            get {
                return ResourceManager.GetString("PluginManagerDeactivateConsumerNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value has to be greater than 0. ähnelt.
        /// </summary>
        internal static string PluginManagerFrameRateTooLow {
            get {
                return ResourceManager.GetString("PluginManagerFrameRateTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopConsumer1Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer1Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopConsumer2Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer2Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopConsumer3Failed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumer3Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems occured when refreshing the display in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopConsumerUIFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopConsumerUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopInterruptFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopInterruptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopProducerFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopProducerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems occured when refreshing the display in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerLoopProducerUIFailed {
            get {
                return ResourceManager.GetString("PluginManagerLoopProducerUIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The plugin could not be loaded. Missing references of plugin {0}. ähnelt.
        /// </summary>
        internal static string PluginManagerMissingReferences {
            get {
                return ResourceManager.GetString("PluginManagerMissingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There were problems loading plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerProducerPluginCommonProblems {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginCommonProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two versions of plugin {0} ({1}) were found. The one with the higher version number will be loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerProducerPluginNewerVersion {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginNewerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A higher version of plugin {0} ({1}) has already been loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerProducerPluginNewerVersionLoaded {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginNewerVersionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The settings of plugin {0} ({1}) could not be loaded. ähnelt.
        /// </summary>
        internal static string PluginManagerProducerPluginSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problems occurred when attempting to save the settings of plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerProducerPluginSettingsSaveFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerPluginSettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem in plugin {0} ({1}). ähnelt.
        /// </summary>
        internal static string PluginManagerProducerVisibilitySetFailed {
            get {
                return ResourceManager.GetString("PluginManagerProducerVisibilitySetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration could not be loaded. This is likely due to an old version. ähnelt.
        /// </summary>
        internal static string PluginManagerSettingsLoadFailed {
            get {
                return ResourceManager.GetString("PluginManagerSettingsLoadFailed", resourceCulture);
            }
        }
    }
}
